name: Notify Discord
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@v3
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            **${{ github.actor }}** pushed to **${{ github.repository }}**
            Branch: `${{ github.ref_name }}`
            Commit: ${{ github.sha }}

